package src.database;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import src.models.Promotion;
//[1] OpenAI. (2025). Code generated by ChatGPT (GPT-5 model) for PromotionCRUD.java. Retrieved November 29, 2025, from https://chat.openai.com/
public class PromotionCRUD {

    //Helper method to create Promotion from ResultSet
    private static Promotion buildPromotion(ResultSet rs) {
        try {
            String id = DB.getString(rs, "promotion_id");
            String title = DB.getString(rs, "title");
            String message = DB.getString(rs, "message");
            String startDateStr = DB.getString(rs, "start_date");
            String endDateStr = DB.getString(rs, "end_date");
            String discountStr = DB.getString(rs, "discount_percent");

            LocalDate startDate = LocalDate.parse(startDateStr);
            LocalDate endDate = LocalDate.parse(endDateStr);
            double discount = Double.parseDouble(discountStr);

            return new Promotion(id, title, message, startDate, endDate, discount);
        } catch (Exception e) {
            System.err.println("Error building promotion: " + e.getMessage());
            return null;
        }
    }

    //Get all promotions
    public static List<Promotion> findAll() {
        List<Promotion> promotions = new ArrayList<>();
        String sql = "SELECT promotion_id, title, message, start_date, end_date, discount_percent FROM promotion";
        
        PreparedStatement stmt = DB.prepare(sql);
        ResultSet rs = DB.query(stmt);

        while (DB.next(rs)) {
            Promotion promo = buildPromotion(rs);
            if (promo != null) {
                promotions.add(promo);
            }
        }

        return promotions;
    }

    //Get promotion by ID
    public static Promotion findById(String promotionId) {
        if (promotionId == null || promotionId.isBlank()) {
            return null;
        }

        String sql = "SELECT promotion_id, title, message, start_date, end_date, discount_percent FROM promotion WHERE promotion_id = ?";
        PreparedStatement stmt = DB.prepare(sql);
        DB.set(stmt, 1, promotionId.trim());
        ResultSet rs = DB.query(stmt);

        if (DB.next(rs)) {
            return buildPromotion(rs);
        }

        return null;
    }

    //Save promotion 
    public static void savePromotion(Promotion promo) {
        if (promo == null) {
            throw new IllegalArgumentException("promotion cannot be null");
        }

        String sql = "INSERT INTO promotion (promotion_id, title, message, start_date, end_date, discount_percent) " +
                     "VALUES (?, ?, ?, ?, ?, ?) " +
                     "ON CONFLICT(promotion_id) DO UPDATE SET " +
                     "  title = excluded.title, " +
                     "  message = excluded.message, " +
                     "  start_date = excluded.start_date, " +
                     "  end_date = excluded.end_date, " +
                     "  discount_percent = excluded.discount_percent";

        PreparedStatement stmt = DB.prepare(sql);
        DB.set(stmt, 1, promo.getPromotionId());
        DB.set(stmt, 2, promo.getTitle());
        DB.set(stmt, 3, promo.getMessage());
        DB.set(stmt, 4, promo.getStartDate().toString());
        DB.set(stmt, 5, promo.getEndDate().toString());
        DB.set(stmt, 6, Double.toString(promo.getDiscountPercent()));

        DB.update(stmt);
    }

    //Delete promotion
    public static void deletePromotion(String promotionId) {
        if (promotionId == null || promotionId.isBlank()) {
            throw new IllegalArgumentException("promotionId is required");
        }

        String sql = "DELETE FROM promotion WHERE promotion_id = ?";
        PreparedStatement stmt = DB.prepare(sql);
        DB.set(stmt, 1, promotionId.trim());
        DB.update(stmt);
    }
}

